---
title: "AE Report"
author: "Nicholas Horton (nhorton@amherst.edu)"
date: "August 6, 2022"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
library(googlesheets4)
library(dbplyr)
library(tidyverse)  
library(kableExtra)
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r, message = FALSE, warning = FALSE}
gs4_deauth()
board <- read_sheet("https://docs.google.com/spreadsheets/d/1MGvhHoNrxp3xxfhu7CHUdmxVMPAU1wvLUNY3DNldDvg/edit#gid=776978137")
  
board <- board %>% 
  # omit empty roles left between sections 
  na.omit() %>%
  mutate(
    name = case_when(
      name == "Gabriella Belli" ~ "Gabriella M. Belli",
      name == "Ann R. Cannon" ~ "Ann Cannon",
      name == "Jackie Miller" ~ "Jack Miller",
      name == "Gudmund Iversen" ~ "Gudmund R. Iversen",
      name == "Margaret Mackisack" ~ "Margaret S. Mackisack",
      name == "William I. Notz" ~ "Bill Notz",
      name == "Deborah J. Rumsey" ~ "Deb Rumsey",
      name == "Jerry Moreno" ~ "Jerry L. Moreno", 
      name == "Joseph Wisenbaker" ~ "Joseph M. Wisenbaker",
      TRUE ~ name
    ),
    role = case_when(
      role == "journals administrator, american statistical association" ~ "journals manager",
      role == "editorial board" ~ "associate editor",
      str_detect(role, "editor, .*") ~ "section editor",
      TRUE ~ role
    )
  )
```

```{r}
name_list <- board %>%
  select(name) %>%
  distinct() %>%
  arrange(name) %>%
  pull()
name_list
```

```{r}
role_list <- board %>%
  select(role) %>%
  distinct() 
tally(~ role_list, data = role_list)
```

```{r eval = FALSE}
activity <- board %>%
  separate(col = year, into = c("year", NA))
tally(~ year, data = activity)
```


